In [1]:
import pandas as pd
import numpy as np

In [2]:
nav = pd.read_csv("../data/processed/02_nav_history_cleaned.csv")
nav.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [3]:
nav = pd.read_csv("../data/processed/02_nav_history_cleaned.csv")
nav.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [4]:
nav["date"] = pd.to_datetime(nav["date"])

nav = nav.sort_values(["amfi_code", "date"])

nav["daily_return"] = nav.groupby("amfi_code")["nav"].pct_change()

nav.head()

   amfi_code       date       nav  daily_return
0     100016 2022-01-03  520.4608           NaN
1     100016 2022-01-04  515.0971     -0.010306
2     100016 2022-01-05  521.7239      0.012865
3     100016 2022-01-06  515.7880     -0.011377
4     100016 2022-01-07  515.1639     -0.001210

In [5]:
var_95 = nav.groupby("amfi_code")["daily_return"].quantile(0.05)

var_95.head()

amfi_code
100016   -0.014364
100025   -0.003793
100033   -0.019034
101206   -0.013282
101207   -0.026021
Name: daily_return, dtype: float64

In [6]:
var_95 = nav.groupby("amfi_code")["daily_return"].quantile(0.05).reset_index()

var_95.columns = ["amfi_code", "VaR_95"]

var_95.head()

   amfi_code    VaR_95
0     100016 -0.014364
1     100025 -0.003793
2     100033 -0.019034
3     101206 -0.013282
4     101207 -0.026021

In [7]:
var_95

    amfi_code    VaR_95
0      100016 -0.014364
1      100025 -0.003793
2      100033 -0.019034
3      101206 -0.013282
4      101207 -0.026021
5      101208 -0.000269
6      102885 -0.012613
7      102886 -0.019220
8      102887 -0.015232
9      118632 -0.013954
10     118633 -0.013443
11     118634 -0.025438
12     118635 -0.012554
13     118636 -0.003804
14     119092 -0.013750
15     119093 -0.014226
16     119094 -0.018480
17     119095 -0.026188
18     119120 -0.003938
19     119551 -0.012846
20     119552 -0.013501
21     119598 -0.024507
22     119599 -0.026859
23     120503 -0.013550
24     120504 -0.013728
25     120505 -0.018892
26     120506 -0.014388
27     120507 -0.000222
28     120841 -0.013142
29     120842 -0.018219
30     120843 -0.014508
31     120844 -0.000285
32     125497 -0.014592
33     125498 -0.018365
34     148567 -0.013560
35     148568 -0.014712
36     148569 -0.017118
37     149322 -0.014474
38     149323 -0.017882
39     149324 -0.023483

In [8]:
var_95.head()

   amfi_code    VaR_95
0     100016 -0.014364
1     100025 -0.003793
2     100033 -0.019034
3     101206 -0.013282
4     101207 -0.026021

In [9]:
cvar_95 = []

for code in nav["amfi_code"].unique():
    fund = nav[nav["amfi_code"] == code]

    var = fund["daily_return"].quantile(0.05)

    cvar = fund[fund["daily_return"] <= var]["daily_return"].mean()

    cvar_95.append([code, cvar])

cvar_95 = pd.DataFrame(cvar_95, columns=["amfi_code", "CVaR_95"])

cvar_95.head()

   amfi_code   CVaR_95
0     100016 -0.018060
1     100025 -0.004994
2     100033 -0.023456
3     101206 -0.017439
4     101207 -0.032459